name: Actions Workflow 

on: 
 pull_request:
  branches:
   - master
   - test
   - 'v*'
  types:
    - opened
    - reopened
    - closed
     
jobs: 
  run-github-actions: 
    runs-on: ubuntu-latest
    steps:
      - name: List Files 
        run: |
          pwd
          ls -a
      - name: Checkout 
        uses: actions/checkout@v1
      - name: List Files After Checkout
        run: |
          pwd
          ls -ltr
          echo ${{inputs.name}}
      - name: Checking bash
        continue-on-error: true
        run : |
          chmod +x check.sh
          ./check.sh
      - name: state
        run : echo "Adding some Markdown content" >> $GITHUB_STEP_SUMMARY
      - name: Simple JS Action
        id: greet 
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: John
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
      - uses: actions/checkout@v2.3.4
      - id: diff
        run: |
          echo Comparing files
          if diff Testfile.txt check.sh >/dev/null; then
            echo "✅ OUTPUT value EQUAL to EXPECTED value!"
          else
            echo "❌ OUTPUT value NOT EQUAL to EXPECTED value!"
            exit 1
          fi
