name: Actions Workflow 

on: 
    push:
     
jobs: 
  run-github-actions: 
    runs-on: ubuntu-latest
    steps:
      - name: List Files 
        run: |
          pwd
          ls -a
      - name: Checkout 
        uses: actions/checkout@v1
      - name: List Files After Checkout
        run: |
          pwd
          ls -ltr
          echo ${{inputs.name}}
      - name: Checking bash
        continue-on-error: true
        run : |
          chmod +x check.sh
          ./check.sh
      - name: state
        run : echo "Adding some Markdown content" >> $GITHUB_STEP_SUMMARY
      - name: Simple JS Action
        id: greet 
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: John
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"
          steps:
      - uses: actions/checkout@v2.3.4
      - uses: GuillaumeFalourd/diff-action@v1
        with:
          first_file_path: Testfile.txt
          second_file_path: Testfile.txt
          expected_result: PASSED  
